DubaiTutor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('main.urls'))
]

main/urls.py
from django.urls import path

from . import views


app_name = 'main'
urlpatterns = [
    path('index/', views.index, name = 'index'),
    path('sign_up/', views.sign_up, name = 'sign_up'),
    path('send_msg/', views.send_msg, name = "send_msg")
]

main/models.py
from django.contrib.auth.models import User
from django.db import models


class Token(models.Model):
    token_code = models.CharField('token_code', max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    user_tg_id = models.CharField(max_length=100, default='')


class Report(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    dateandtime = models.TimeField()
    text = models.TextField()

main/views.py
import uuid

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from telebot import TeleBot
from .models import Report
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView
from uuid import uuid4
from .models import Token
from datetime import datetime

bot = TeleBot('6547124745:AAHkES88LxUctgqCUuHj13wWxaX98yVrUTc', parse_mode=None)


def index(request):
    try:
        token = Token.objects.get(user = request.user).token_code
    except Exception as ex:
        token = 'not authenticated yet'
        print(ex)
    print(token)
    return render(request, 'main/index.html', {'token': token})


@login_required
def send_msg(request):
    msg = request.POST['input']
    tg_id = Token.objects.get(user = request.user).user_tg_id
    bot.send_message(tg_id, msg)
    report = Report.objects.create(user = request.user, dateandtime = datetime.now(), text = msg)
    return render(request, 'main/index.html', {})


def sign_up(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            token = str(uuid.uuid4())
            user = User.objects.get(username = request.POST['username'])
            token = Token.objects.create(user = user, token_code = request.POST['username'] + token)
            return redirect('login')
        else:
            return render(request, 'registration/sign_up.html', {'form': form})
    if request.method == 'GET':
        form = UserCreationForm()
        return render(request, 'registration/sign_up.html', {'form': form})

templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% block main %}

    {% endblock %}
</body>
</html>

templates/main/index.html
{% extends 'main/base.html' %}
{% block main %}
    <h1>{{ user.username }}</h1>
    <div class="authentication">
        {% if user.is_authenticated %}
            <a href="{% url 'logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'login' %}">login</a>
        {% endif %}
        <a href="{% url 'main:sign_up' %}">Sign Up</a>
    </div>
    <form action="{% url 'main:send_msg' %}" method = "POST">
        {% csrf_token %}
        <input type="text" placeholder = 'input text' name = "input">
        <button type = 'submit'>Submit</button>
    </form>
    <div class="token">
        <p>{{ token }}</p>
    </div>
{% endblock %}